### ISSUE TITLE
incorrect card information or image

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#570]
1) Angel of Glory's Rise [2013 Foil]  PRES shows the incorrect picture

2) Phalanx Leader [Promo Foil] THS .. is not a foil so name should be   Phalanx Leader [Promo]

3) Soulblade Renewer  BBD is listed as a Multicolor card but it is a green card

4) Djinn Iluminatus  GPT prerelease stamped card is missing

5) Wastes (2)  and Wastes (4)  OGW have the wrong picture and card number (they are supposed to be the full art versions)

**Comment by gaddlord** [comment]
1. Angel of Glory's Rise [2013 Foil] PRES shows the incorrect picture.
Updated with https://scryfall.com/card/pres/A9/angel-of-glorys-rise

2. Phalanx Leader [Promo Foil] THS .. is not a foil so name should be Phalanx Leader [Promo]
Fixed. Removed Foil from the name. Fixed in MTG Studio version 3.201.

3. Soulblade Renewer BBD is listed as a Multicolor card but it is a green card
Fixed in MTG Studio version 3.201

4.Djinn Iluminatus GPT prerelease stamped card is missing
Available in 3.200 as "Djinn Illuminatus [Promo 21 Jan 2006 Foil]"

5. Wastes (2) and Wastes (4) OGW have the wrong picture and card number (they are supposed to be the full art versions)
Updated the card Wastes (1) and Wastes (3) with the correct fill art images from:
https://scryfall.com/card/ogw/183/wastes
https://scryfall.com/card/ogw/184/wastes
Wastes (2) and Wastes (4) stay with the "Small Art" images.
